spring:  
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  cloud:
    stream: 
      kafka:
        binder:
          # Kafka的服务端列表
          brokers: 172.40.2.124:9092,172.40.2.125:9092
          # Kafka服务端连接的ZooKeeper节点列表
          #zkNodes: 172.40.2.124:2181,172.40.2.125:2181
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.40.2.115:8761/eureka,http://172.40.2.116:8761/eureka
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳之后等待的过期时间上限，单位为秒。
    #超过该时间没有收到心跳，则服务端会将该服务实例从服务清单中剔除，从而禁止服务调用请求被发送到该实例上
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  #server:
     #port: 12000
     #servlet:
       #context-path: /
  
turbine:
  stream:
    enabled: true
  cluster-name-expression: "'default'"
  app-config: citylife-fw-api-gateway-zuul
  #ccf-gateway-app,ccf-certification-app,sasweb,sasweb-basecode,sasweb-linerimport,sasweb-linerexport,sasweb-serviceproduct,sasweb-exception,sasweb-intertran